apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fairwave.fullname" . }}-data
  labels:
    {{- include "fairwave.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.control.dataStorage }}
