variable "project" {
  description = "Project/tag prefix"
  type        = string
  default     = "fairwave"
}

variable "region" {
  description = "AWS region for the hub"
  type        = string
  default     = "us-east-1"
}

variable "vpc_id" {
  description = "VPC to place the hub in (default = the default VPC of the region)"
  type        = string
}

variable "instance_type" {
  description = "Hub instance type"
  type        = string
  default     = "t3.medium"
}

variable "ssh_key_name" {
  description = "Existing AWS key pair name for SSH access"
  type        = string
}

variable "wg_private_key" {
  description = "WireGuard base64 private key for the hub (generated by fairwave-control — NEVER commit a real key)"
  type        = string
  sensitive   = true
}

variable "wg_port" {
  description = "WireGuard listen port"
  type        = number
  default     = 51820
}

variable "hub_wg_address" {
  description = "WireGuard address of the hub inside the mesh (e.g. 10.99.0.1/16)"
  type        = string
  default     = "10.99.0.1/16"
}

variable "allocate_eip" {
  description = "Allocate and attach an Elastic IP to the hub"
  type        = bool
  default     = true
}
