// Package southbound drives Open5GS and srsRAN via config templating and
// process supervision. v0.1 targets the "config + docker exec" driver;
// the k8s operator style arrives with the Helm charts.
package southbound

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
	"time"
)

// Open5GSConfig is the minimal templated EPC config (4G path).
type Open5GSConfig struct {
	MCC     string
	MNC     string
	TAC     int
	APNs    []string
	UE      string // PGW ue_pool, e.g. 10.45.0.0/16
	DNS1    string
	DNS2    string
	MMEGTPC string // MME S11 address
	Mongo   string // mongodb URI for HSS
}

const open5gsTpl = `# Generated by fairwave-control - DO NOT EDIT BY HAND.
# Template: core/open5gs/open5gs.yaml
global:
  max:
    ue: 1024

mme:
  gtpc:
    addr: {{.MMEGTPC}}
  s1ap:
    addr: 0.0.0.0

sgw:
  gtpc:
    addr: 127.0.0.1
  gtpu:
    addr: 127.0.0.1

pgw:
  gtpc:
    addr: 127.0.0.1
  gtpu:
    addr: 127.0.0.1
  ue_pool:
    - {{.UE}}
  apn:
    - 8.8.8.8/8
    - 1.1.1.1/8
  dns:
    - {{.DNS1}}
    - {{.DNS2}}

hss:
  db:
    uri: {{.Mongo}}
    name: open5gs

pcrf:
  gtpc:
    addr: 127.0.0.1

parameters:
  max:
    ue: 1024
`

// RenderOpen5GS writes the EPC config to dir/open5gs.yaml.
func RenderOpen5GS(ctx context.Context, dir string, cfg Open5GSConfig) (string, error) {
	if cfg.Mongo == "" {
		cfg.Mongo = "mongodb://mongo:27017"
	}
	if cfg.MMEGTPC == "" {
		cfg.MMEGTPC = "127.0.0.1"
	}
	if cfg.DNS1 == "" {
		cfg.DNS1 = "8.8.8.8"
	}
	if cfg.DNS2 == "" {
		cfg.DNS2 = "1.1.1.1"
	}
	if cfg.UE == "" {
		cfg.UE = "10.45.0.0/16"
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	tpl, err := template.New("open5gs").Parse(open5gsTpl)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "open5gs.yaml")
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tpl.Execute(f, cfg); err != nil {
		return "", err
	}
	return path, nil
}

// SrsranENBConfig is the eNB radio config (zmq or RF).
type SrsranENBConfig struct {
	MCC     string
	MNC     string
	TAC     int
	Earfcn  int
	Device  string // zmq | uhd | lime | bladerf
	RFArgs  string // device args
	TxGain  int
	RxGain  int
	MMEAddr string // S1-MME address
}

const enbTpl = `# Generated by fairwave-control - lab or licensed RF operation only.
enb:
  enb_id: 0x1
  cell_id: 0x1
  tac: {{.TAC}}
  plmn:
    mcc: {{.MCC}}
    mnc: {{.MNC}}

rf:
  device_name: {{.Device}}
  device_args: {{.RFArgs}}
  tx_gain: {{.TxGain}}
  rx_gain: {{.RxGain}}

pdcp:
  max_ul_bitrate: 100000000
  max_dl_bitrate: 100000000

s1ap:
  mme_addr: {{.MMEAddr}}
`

// RenderENB writes the eNB config and returns its path.
func RenderENB(ctx context.Context, dir string, cfg SrsranENBConfig) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if cfg.Device == "" {
		cfg.Device = "zmq"
	}
	tpl, err := template.New("enb").Parse(enbTpl)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "enb.yml")
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tpl.Execute(f, cfg); err != nil {
		return "", err
	}
	return path, nil
}

// RestartService runs `docker restart <name>` (driver=docker) or `systemctl
// restart <unit>` (driver=none on systemd hosts). Returns an error if the
// driver can't be executed.
func RestartService(ctx context.Context, driver, name string) error {
	if driver == "none" {
		return nil // no supervision configured (lab direct-run)
	}
	var cmd *exec.Cmd
	switch driver {
	case "docker":
		cmd = exec.CommandContext(ctx, "docker", "restart", name)
	case "systemd":
		cmd = exec.CommandContext(ctx, "systemctl", "restart", name)
	default:
		return fmt.Errorf("unknown southbound driver %q", driver)
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("restart %s: %v: %s", name, err, out)
	}
	_ = time.Now()
	return nil
}
